plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
}

group = 'com.eric.luciernagas'
version = '1.0.0'

base {
    archivesName = 'luciernagas'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'official', version: '1.20.1'
    copyIdeResources = true

    runs {
        configureEach {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'

            mods {
                luciernagas {
                    source sourceSets.main
                }
            }
        }

        client {
        }

        server {
            args '--nogui'
        }
    }
}

repositories {
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.3.0'
}

tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [
            minecraft_version: '1.20.1',
            minecraft_version_range: '[1.20.1,1.21)',
            forge_version: '47.3.0',
            forge_version_range: '[47,)',
            loader_version_range: '[47,)',
            mod_id: 'luciernagas',
            mod_name: 'Luciernagas',
            mod_license: 'MIT',
            mod_version: project.version,
            mod_authors: 'Eric',
            mod_description: 'Luciernagas azules, amarillas, verdes y rosas que aparecen de noche, iluminan, se pueden domesticar y seguir ordenes.'
    ]

    inputs.properties replaceProperties

    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand replaceProperties
    }
}

jar {
    manifest {
        attributes([
                'Specification-Title': 'Luciernagas',
                'Specification-Vendor': 'Eric',
                'Specification-Version': '1',
                'Implementation-Title': project.name,
                'Implementation-Version': project.version,
                'Implementation-Vendor': 'Eric'
        ])
    }
}

jar.finalizedBy('reobfJar')
